FROM ocaml/opam:debian-11-ocaml-4.14@sha256:563c777e7afb14b865ba71d74e1de9a278d8a218e9a544af50b070926de31189 AS build
RUN sudo apt-get update && sudo apt-get install libev-dev capnproto m4 pkg-config libgmp-dev libssl-dev libsqlite3-dev -y --no-install-recommends
RUN cd ~/opam-repository && git fetch -q origin master && git reset --hard 4031ecb15837a767eb86fdfb23f20aa529d1d059 && opam update
COPY --chown=opam \
	ocurrent/current_rpc.opam \
	/src/ocurrent/
WORKDIR /src
RUN opam pin -yn add ./ocurrent
COPY --chown=opam ocaml-ci-api.opam ocaml-ci-web.opam ocaml-ci-client-lib.opam /src/
RUN opam install -y --deps-only .
ADD --chown=opam . .
RUN opam config exec -- dune build ./_build/install/default/bin/ocaml-ci-web

FROM debian:11
RUN apt-get update && apt-get install libev4 curl jq dumb-init -y --no-install-recommends
WORKDIR /
ENTRYPOINT ["dumb-init", "/usr/local/bin/ocaml-ci-web"]

RUN apt-get install ca-certificates -y  # https://github.com/mirage/ocaml-conduit/issues/388
COPY --from=build /src/_build/install/default/bin/ocaml-ci-web /usr/local/bin/

## Load profile-pictures of registered organisations
RUN mkdir -p /profile-pictures/github
RUN mkdir -p /profile-pictures/gitlab
COPY --from=build /src/bin/add-profile-picture /usr/local/bin
COPY --from=build /src/deploy-data/github-organisations.txt /github-organisations.txt
COPY --from=build /src/deploy-data/gitlab-organisations.txt /gitlab-organisations.txt
RUN xargs -n 1 /usr/local/bin/add-profile-picture --github < /github-organisations.txt
RUN xargs -n 1 /usr/local/bin/add-profile-picture --gitlab < /gitlab-organisations.txt
